# Generated by Django 3.0.8 on 2020-08-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200721_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communities_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='admins_post',
            name='admin_author',
        ),
        migrations.RemoveField(
            model_name='admins_post',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='admins_post',
            name='description',
        ),
        migrations.AddField(
            model_name='admins_post',
            name='admins_info',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admins_post',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Communites_Post',
        ),
    ]
