# Generated by Django 3.0.8 on 2020-08-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200805_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communities_Post',
            new_name='post',
        ),
    ]
